### ISSUE TITLE
The icon has vanished in the last 2 updates. 

### ISSUE THREAD

**Issue by Apollo702** [fwenzel/copy-url#6]
Thank you for staying with your add-on and updating it. However, with the last 2 updates the icon has vanished on each of my machines. Both run Palemoon and I supposed I could install it in Failfox to test it out there too. 

Please look into it when you can and thank you in advance!

**Comment by fwenzel** [comment]
Updating the add-on for the latest versions of Firefox right now, closing out this bug because I assume it'll work in PM as well.
